module.exports = {
	root: 'dist',
	cacheId: '',
	clientsClaim: true,
	directoryIndex: 'index.html',
	dontCacheBustUrlsMatching: null,
	dynamicUrlToDependencies: {},
	handleFetch: true,
	ignoreUrlParametersMatching: [/^utm_/],
	importScripts: [],
	logger: console.log,
	maximumFileSizeToCacheInBytes: 2097152,
	navigateFallback: 'index.html',
	navigateFallbackWhitelist: [],
	replacePrefix: '',
	runtimeCaching: [],
	skipWaiting: true,
	staticFileGlobs: [],
	stripPrefix: 'dist/',
	stripPrefixMulti: {},
	templateFilePath: '',
	verbose: false
}
